labels:
  0: 'free'
  1: 'background'
  2: 'vehicle'
  3: 'bicycle'
  4: 'pedestrian'
  5: 'traffic_cone'
  6: 'barrier'
  7: 'czone_sign'
  8: 'generic_object'


learning_map:
  0: 0
  1: 1
  2: 2
  3: 3
  4: 4
  5: 5
  6: 6
  7: 7
  8: 8
